<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Ei_alocados_totalizacao_model extends MY_Model
{
	protected static $table = 'ei_alocados_totalizacao';

	protected $validationRules = [
		'id' => 'required|is_natural_no_zero|max_length[11]',
		'id_alocado' => 'required|is_natural_no_zero|max_length[11]',
		'periodo' => 'numeric|max_length[1]',
		'total_dias_mes1' => 'integer|max_length[2]',
		'total_dias_mes2' => 'integer|max_length[2]',
		'total_dias_mes3' => 'integer|max_length[2]',
		'total_dias_mes4' => 'integer|max_length[2]',
		'total_dias_mes5' => 'integer|max_length[2]',
		'total_dias_mes6' => 'integer|max_length[2]',
		'total_dias_mes7' => 'integer|max_length[2]',
		'total_dias_sub1' => 'integer|max_length[2]',
		'total_dias_sub2' => 'integer|max_length[2]',
		'total_horas_mes1' => 'valid_time',
		'total_horas_mes2' => 'valid_time',
		'total_horas_mes3' => 'valid_time',
		'total_horas_mes4' => 'valid_time',
		'total_horas_mes5' => 'valid_time',
		'total_horas_mes6' => 'valid_time',
		'total_horas_mes7' => 'valid_time',
		'total_horas_sub1' => 'valid_time',
		'total_horas_sub2' => 'valid_time',
		'horas_descontadas_mes1' => 'valid_time',
		'horas_descontadas_mes2' => 'valid_time',
		'horas_descontadas_mes3' => 'valid_time',
		'horas_descontadas_mes4' => 'valid_time',
		'horas_descontadas_mes5' => 'valid_time',
		'horas_descontadas_mes6' => 'valid_time',
		'horas_descontadas_mes7' => 'valid_time',
		'horas_descontadas_sub1' => 'valid_time',
		'horas_descontadas_sub2' => 'valid_time',
		'data_aprovacao_mes1' => 'valid_date',
		'data_aprovacao_mes2' => 'valid_date',
		'data_aprovacao_mes3' => 'valid_date',
		'data_aprovacao_mes4' => 'valid_date',
		'data_aprovacao_mes5' => 'valid_date',
		'data_aprovacao_mes6' => 'valid_date',
		'data_aprovacao_mes7' => 'valid_date',
		'data_aprovacao_sub1' => 'valid_date',
		'data_aprovacao_sub2' => 'valid_date',
		'data_impressao_mes1' => 'valid_date',
		'data_impressao_mes2' => 'valid_date',
		'data_impressao_mes3' => 'valid_date',
		'data_impressao_mes4' => 'valid_date',
		'data_impressao_mes5' => 'valid_date',
		'data_impressao_mes6' => 'valid_date',
		'data_impressao_mes7' => 'valid_date',
		'data_impressao_sub1' => 'valid_date',
		'data_impressao_sub2' => 'valid_date',
		'total_horas_faturadas_mes1' => 'valid_time',
		'total_horas_faturadas_mes2' => 'valid_time',
		'total_horas_faturadas_mes3' => 'valid_time',
		'total_horas_faturadas_mes4' => 'valid_time',
		'total_horas_faturadas_mes5' => 'valid_time',
		'total_horas_faturadas_mes6' => 'valid_time',
		'total_horas_faturadas_mes7' => 'valid_time',
		'total_horas_faturadas_sub1' => 'valid_time',
		'total_horas_faturadas_sub2' => 'valid_time',
		'valor_pagamento_mes1' => 'decimal|max_length[11]',
		'valor_pagamento_mes2' => 'decimal|max_length[11]',
		'valor_pagamento_mes3' => 'decimal|max_length[11]',
		'valor_pagamento_mes4' => 'decimal|max_length[11]',
		'valor_pagamento_mes5' => 'decimal|max_length[11]',
		'valor_pagamento_mes6' => 'decimal|max_length[11]',
		'valor_pagamento_mes7' => 'decimal|max_length[11]',
		'valor_pagamento_sub1' => 'decimal|max_length[11]',
		'valor_pagamento_sub2' => 'decimal|max_length[11]',
		'valor_total_mes1' => 'decimal|max_length[11]',
		'valor_total_mes2' => 'decimal|max_length[11]',
		'valor_total_mes3' => 'decimal|max_length[11]',
		'valor_total_mes4' => 'decimal|max_length[11]',
		'valor_total_mes5' => 'decimal|max_length[11]',
		'valor_total_mes6' => 'decimal|max_length[11]',
		'valor_total_mes7' => 'decimal|max_length[11]',
		'valor_total_sub1' => 'decimal|max_length[11]',
		'valor_total_sub2' => 'decimal|max_length[11]'
	];

}
