<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class Ei_pagamento_prestador_model extends MY_Model
{
	protected static $table = 'ei_pagamento_prestador';

	protected $validationRules = [
		'id' => 'required|is_natural_no_zero|max_length[11]',
		'id_alocacao' => 'required|is_natural_no_zero|max_length[11]',
		'id_cuidador' => 'is_natural_no_zero|max_length[11]',
		'cuidador' => 'max_length[255]',
		'cargo' => 'max_length[255]',
		'funcao' => 'max_length[255]',
		'nota_fiscal_mes1' => 'max_length[255]',
		'nota_fiscal_mes2' => 'max_length[255]',
		'nota_fiscal_mes3' => 'max_length[255]',
		'nota_fiscal_mes4' => 'max_length[255]',
		'nota_fiscal_mes5' => 'max_length[255]',
		'nota_fiscal_mes6' => 'max_length[255]',
		'nota_fiscal_mes7' => 'max_length[255]',
		'valor_extra1_mes1' => 'decimal|max_length[11]',
		'valor_extra1_mes2' => 'decimal|max_length[11]',
		'valor_extra1_mes3' => 'decimal|max_length[11]',
		'valor_extra1_mes4' => 'decimal|max_length[11]',
		'valor_extra1_mes5' => 'decimal|max_length[11]',
		'valor_extra1_mes6' => 'decimal|max_length[11]',
		'valor_extra1_mes7' => 'decimal|max_length[11]',
		'valor_extra2_mes1' => 'decimal|max_length[11]',
		'valor_extra2_mes2' => 'decimal|max_length[11]',
		'valor_extra2_mes3' => 'decimal|max_length[11]',
		'valor_extra2_mes4' => 'decimal|max_length[11]',
		'valor_extra2_mes5' => 'decimal|max_length[11]',
		'valor_extra2_mes6' => 'decimal|max_length[11]',
		'valor_extra2_mes7' => 'decimal|max_length[11]',
		'justificativa1_mes1' => 'max_length[65535]',
		'justificativa1_mes2' => 'max_length[65535]',
		'justificativa1_mes3' => 'max_length[65535]',
		'justificativa1_mes4' => 'max_length[65535]',
		'justificativa1_mes5' => 'max_length[65535]',
		'justificativa1_mes6' => 'max_length[65535]',
		'justificativa1_mes7' => 'max_length[65535]',
		'justificativa2_mes1' => 'max_length[65535]',
		'justificativa2_mes2' => 'max_length[65535]',
		'justificativa2_mes3' => 'max_length[65535]',
		'justificativa2_mes4' => 'max_length[65535]',
		'justificativa2_mes5' => 'max_length[65535]',
		'justificativa2_mes6' => 'max_length[65535]',
		'justificativa2_mes7' => 'max_length[65535]',
		'data_liberacao_pagto_mes1' => 'valid_date',
		'data_liberacao_pagto_mes2' => 'valid_date',
		'data_liberacao_pagto_mes3' => 'valid_date',
		'data_liberacao_pagto_mes4' => 'valid_date',
		'data_liberacao_pagto_mes5' => 'valid_date',
		'data_liberacao_pagto_mes6' => 'valid_date',
		'data_liberacao_pagto_mes7' => 'valid_date',
		'data_inicio_contrato_mes1' => 'valid_date',
		'data_inicio_contrato_mes2' => 'valid_date',
		'data_inicio_contrato_mes3' => 'valid_date',
		'data_inicio_contrato_mes4' => 'valid_date',
		'data_inicio_contrato_mes5' => 'valid_date',
		'data_inicio_contrato_mes6' => 'valid_date',
		'data_inicio_contrato_mes7' => 'valid_date',
		'data_termino_contrato_mes1' => 'valid_date',
		'data_termino_contrato_mes2' => 'valid_date',
		'data_termino_contrato_mes3' => 'valid_date',
		'data_termino_contrato_mes4' => 'valid_date',
		'data_termino_contrato_mes5' => 'valid_date',
		'data_termino_contrato_mes6' => 'valid_date',
		'data_termino_contrato_mes7' => 'valid_date',
		'pagamento_proporcional_inicio' => 'numeric|max_length[1]',
		'pagamento_proporcional_termino' => 'numeric|max_length[1]',
		'tipo_pagamento_mes1' => 'numeric|max_length[1]',
		'tipo_pagamento_mes2' => 'numeric|max_length[1]',
		'tipo_pagamento_mes3' => 'numeric|max_length[1]',
		'tipo_pagamento_mes4' => 'numeric|max_length[1]',
		'tipo_pagamento_mes5' => 'numeric|max_length[1]',
		'tipo_pagamento_mes6' => 'numeric|max_length[1]',
		'tipo_pagamento_mes7' => 'numeric|max_length[1]',
		'observacoes_mes1' => 'max_length[4294967295]',
		'observacoes_mes2' => 'max_length[4294967295]',
		'observacoes_mes3' => 'max_length[4294967295]',
		'observacoes_mes4' => 'max_length[4294967295]',
		'observacoes_mes5' => 'max_length[4294967295]',
		'observacoes_mes6' => 'max_length[4294967295]',
		'observacoes_mes7' => 'max_length[4294967295]'
	];

}
